### ISSUE TITLE
A list of optons

### ISSUE THREAD

**Issue by Sivli-Embir** [ccorcos/meteor-animate#1]
First off great work, keep it up! However both you animation packages say:

> The easiest is to pass a VelocityJS UI Pack pre-registered effect as a string.

Having no experience with velocity.js its not very obvious what strings you are talking about. Would you mind clarifying a bit more? Just to help others (me) get a head start ^_^

**Comment by ccorcos** [comment]
Updated the readme for you. But to answer your question.

Go [here](http://julian.com/research/velocity/#uiPack). Find the "Effects: Pre-Registered" section and play around with that dropdown menu. Those are all the pre-registered effects. You can also register your own effects -- thats also explained in the velocity documentation, but you can also see it in action [here](https://github.com/julianshapiro/velocity/blob/master/velocity.ui.js#L299) and [here](https://github.com/ccorcos/meteor-animate/blob/master/example/client/main.coffee#L2).

**Comment by Sivli-Embir** [comment]
Ah 'Effects: Pre-Registered' is what I was missing. Thanks that really helps.
